FROM ubuntu

RUN \
	apt-get update && apt-get --no-install-recommends -y -q install curl && apt-get --no-install-recommends -y -q install unzip && apt-get --no-install-recommends -y -q install git

	curl https://storage.googleapis.com/dart-archive/channels/stable/release/2.0.0/sdk/dartsdk-linux-arm-release.zip -o dart.zip
unzip dart.zip

	unzip dart.zip
